debug: true

server:
  port: 8000
  tomcat:
    uri-encoding: UTF-8
    basedir: ./
    accesslog:
      enabled: true
      request-attributes-enabled: true
  compression:
    enabled: true
  servlet:
    context-path: /spring-boot-demo

spring:
  application:
    name: spring-boot-demo
  profiles:
    active: default
  jpa:
    properties:
      hibernate.enable_lazy_load_no_trans: true
  output:
    ansi:
      enabled: detect

# 日志配置
logging:
  file: ./logs/shop-manage-server.log
  level:
    me.frank.demo: debug
    jdbc.sqlonly: debug
    jdbc.resultsettable: debug
    jdbc.audit: error
    jdbc.resultset: error
    jdbc.sqltiming: error
    jdbc.connection: error
    org.springframework.web.servlet: warn
    org.springframework.boot.actuate.endpoint.mvc: warn
    springfox.documentation: warn
    com.zaxxer.hikari.pool.HikariPool: warn
    org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener: warn
    org.springframework.boot.actuate.endpoint.web.servlet.ControllerEndpointHandlerMapping: warn
    org.springframework.boot.actuate.endpoint.web.servlet.WebMvcEndpointHandlerMapping: warn
    org.springframework.boot.web.servlet.filter.OrderedRequestContextFilter: warn

# MyBatis配置
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:me/frank/demo/mapper/*Mapper.xml
  type-aliases-package: me.frank.demo.entity

# jwt配置
jwt:
  valid-duration: 86400000
  encrypt-key: 9Z5g6M4%9btE

# 数据库参数
hikari:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    maximum-pool-size: 30
    max-lifetime: 1800000
    minimum-idle: 20
    idle-timeout: 100000
    driver-class-name: com.mysql.jdbc.Driver

# Shiro
shiro:
  sessionManager:
    sessionIdCookieEnabled: false
    sessionIdUrlRewritingEnabled: false